<?php

namespace Modules\Hotel\Models;

use Modules\Base\Models\Model;

class Building extends Model
{
    public $type = 'building';
    protected $table = 'bravo_building';
    protected $modelName = Building::class;
    protected $transClass = BuildingTranslation::class;
    protected $fieldClone = "name";

    protected $fillable = [
        'name',
    ];

    public function __toString()
    {
        return sprintf('%s', $this->name ?: '');
    }

    public function delete()
    {
        if ($this->floors) {
            foreach ($this->floors as $floor) {
                $floor->delete();
            }
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function floors()
    {
        return $this->hasMany(BuildingFloor::class, 'building_id', 'id');
    }
}
