<?php

namespace Modules\Hotel\Models;

use Illuminate\Support\Facades\DB;
use Modules\Base\Models\Model;

class Building extends Model
{
    public $type = 'building';
    protected $table = 'bravo_building';
    protected $modelName = Building::class;
    protected $transClass = BuildingTranslation::class;
    protected $fieldClone = "name";

    protected $fillable = [
        'name',
    ];

    public function __toString()
    {
        return sprintf('%s', $this->name ?: '');
    }

    public function delete()
    {
        if ($this->floors) {
            foreach ($this->floors as $floor) {
                $floor->delete();
            }
        }

        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function floors()
    {
        return $this->hasMany(BuildingFloor::class, 'building_id', 'id');
    }

    public function floorByID($id)
    {
        return BuildingFloor::query()->find($id);
    }

    public static function getForSelect2Query($q)
    {
        $query =  static::query()->select(
            'id', DB::raw('name as text'))
            ->Where("name", 'like', '%' . $q . '%');

        return $query;
    }

    public function getDisplayName()
    {
        return sprintf('%s', $this->name);
    }
}
